nodeLinker: node-modules #Chỉ định cách Yarn liên kết các gói với các thư viện phụ thuộc. Có hai giá trị hợp lệ: "node-modules" và "pnp".

plugins: # sử dụng các plugin để mở rộng các chức năng hoặc tăng cường hiệu suất của Yarn.
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs #@yarnpkg/plugin-workspace-tools là một plugin Yarn hỗ trợ cho việc quản lý các workspace (không gian làm việc) trong một dự án lớn. Workspace là một tính năng của Yarn cho phép bạn quản lý nhiều package trong một repository duy nhất và giải quyết các vấn đề về phụ thuộc giữa chúng một cách hiệu quả.
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.4.1.cjs
#npmRegistryServer: Chỉ định registry npm để sử dụng khi cài đặt các gói.
#preferredCacheFolder: Chỉ định thư mục để lưu trữ bộ nhớ đệm Yarn.
#enableImmutableInstalls: Khi được thiết lập thành true, Yarn sử dụng một chế độ cài đặt bất biến, nghĩa là mỗi lần cài đặt một phụ thuộc, Yarn sẽ tạo ra một phiên bản mới của thư mục node_modules, thay vì chỉnh sửa phiên bản hiện có.
#cacheFolder: Chỉ định thư mục để lưu trữ bộ nhớ đệm Yarn.
